<?php
return[
    'txt_title' => 'ABOUT ICETy',
    'txt_cleanmag' => 'The first magazine about cleanliness in Indonesia and Asia. This magazine presents the latest information, news & trends, tips & tricks about the tourism industry. Technological advances in the areas of cleanliness, sanitation, and the environment will also be highlighted in CleanM@g. Various content is presented using OME (Online Media Experience), which makes the reading experience much more enjoyable and entertaining.',
    'txt_educleaning_1' => 'Educleaning123 is a series of knowledge management products in e-book and printed books. This book is a one stop of information and knowledge for industrial needs. For instance, executives in the hospitality industry and public service (E.g. : education institution, food service industry, associations, and building management industry).',
    'txt_educleaning_2' => 'Educleaning123 is a series of knowledge management products in e-book and printed books. This book is a “One Stop Information and Knowledge” in enhancing Indonesia’s hospitality industry. Target readers are all people in hospitality and public service industry, such as management & staff in hospitality industry, hospitality and tourism schools, food service industry, associations (PHRI, IHKA, APKLINDO, ATI, ACP, APCA,etc), building management, and other related industries. The educational content in Educleaning123 is served in an unique and interesting way through the concept of OME (Online Media Experience). This concept provides the best experience for readers with more fun and entertaining by using the latest digital media integrated in the ICETy digital platform.',
    'txt_oce_1' => 'An online course module (Learning Management System) that provides various practical solutions (skills and knowledge) needed to manage the hygiene, sanitation, and environmental aspects of the tourism industry. This module utilizes various digital communication media with streaming or online videos presented in a 360-degree experience, using VR (virtual reality) and AR (augmented reality).',
    'txt_oce_2' => 'The OCE module was specially produced by ICETy with the involvement of various experts, industry practitioners, professional associations, certification bodies, and policy makers.'
];
