name : Deploy tbh-v3 to prod
on:
  push:
    branches: [ main ]

jobs:
  first:
    name: Pull from github
    runs-on: ubuntu-latest
    steps:
    - name: deploy tbh-icety - pulling
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.DIR_PROD }}
          git pull origin main && composer install && composer update && php artisan optimize
          php artisan config:clear
