name : Deploy tbh-v3 to testing
on:
  push:
    branches: [ dev-testing ]

jobs:
  first:
    name: Pull from github
    runs-on: ubuntu-latest
    steps:
    - name: deploy tbh-icety - pulling
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_PROD }}
        username: ${{ secrets.USER_DEV }}
        key: ${{ secrets.MY_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.DIR_DEV }}
          git config --global --add safe.directory ${{ secrets.DIR_DEV }}
          git pull origin dev-testing && composer install && composer update && php artisan optimize
          php artisan config:clear
